/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_alfa;

import com.jcraft.jsch.*;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.net.Socket;
import java.net.SocketException;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;

/**
 *
 * @author adrix
 */

public class appframe extends javax.swing.JFrame {

    public static String komenda = "";
    public static String USER = "";
    public static String PASS = "";
    public static String host = "";
    public static String ip_route = "";
    public static String full_get_selected = "";
    public static String ip_addr_glob = "";
    public static String file_path_glob = "";
    public static int port = 22;

    /**
     * Creates new form appframe
     */
    public appframe() {
        setTitle("");
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.JPanel();
        jP1 = new javax.swing.JPanel();
        Title_jP1 = new javax.swing.JLabel();
        Subtitle_jP1 = new javax.swing.JLabel();
        Title_combobox_jP1 = new javax.swing.JLabel();
        rpilist_jP1 = new javax.swing.JComboBox<>();
        Panel_jP1 = new javax.swing.JPanel();
        Refresh_jP1 = new javax.swing.JButton();
        Next_jP1 = new javax.swing.JButton();
        jP2 = new javax.swing.JPanel();
        Title_jP2 = new javax.swing.JLabel();
        Subtitle_jP2 = new javax.swing.JLabel();
        username_title_jP2 = new javax.swing.JLabel();
        username_jP2 = new javax.swing.JTextField();
        password_title_jP2 = new javax.swing.JLabel();
        password_jP2 = new javax.swing.JPasswordField();
        Panel_jP2 = new javax.swing.JPanel();
        Next_jP2 = new javax.swing.JButton();
        Back_jP2 = new javax.swing.JButton();
        jP3 = new javax.swing.JPanel();
        Title_jP3 = new javax.swing.JLabel();
        Subtitle_jP3 = new javax.swing.JLabel();
        create_jP3 = new javax.swing.JButton();
        send_jP3 = new javax.swing.JButton();
        Panel_jP3 = new javax.swing.JPanel();
        Back_jP3 = new javax.swing.JButton();
        jP4_create = new javax.swing.JPanel();
        Title_jP4 = new javax.swing.JLabel();
        Subtitle_jP4 = new javax.swing.JLabel();
        Panel_jP4 = new javax.swing.JPanel();
        Next_jP4 = new javax.swing.JButton();
        Back_jP4 = new javax.swing.JButton();
        jP5_send = new javax.swing.JPanel();
        Title_jP5 = new javax.swing.JLabel();
        Subtitle_jP5 = new javax.swing.JLabel();
        select_file_jP5 = new javax.swing.JButton();
        file_path_jP5 = new javax.swing.JTextField();
        Panel_jP5 = new javax.swing.JPanel();
        Next_jP5 = new javax.swing.JButton();
        Back_jP5 = new javax.swing.JButton();
        send_button_jP5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P1.setLayout(new java.awt.CardLayout());

        jP1.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP1.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP1.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP1.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP1.setText("Witaj!");
        Title_jP1.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP1.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP1.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP1.setText("Aby kontynuować wybierz swoje urządzenie z listy poniżej...");
        Subtitle_jP1.setPreferredSize(new java.awt.Dimension(503, 24));

        Title_combobox_jP1.setForeground(new java.awt.Color(149, 152, 154));
        Title_combobox_jP1.setText("Urządzenia podłączone do sieci...");

        rpilist_jP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Przed użyciem odśwież listę urządzeń" }));
        rpilist_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpilist_jP1ActionPerformed(evt);
            }
        });

        Panel_jP1.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP1.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP1.setPreferredSize(new java.awt.Dimension(88, 59));

        Refresh_jP1.setText("Odśwież listę");
        Refresh_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_jP1ActionPerformed(evt);
            }
        });

        Next_jP1.setText("Dalej");
        Next_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP1Layout = new javax.swing.GroupLayout(Panel_jP1);
        Panel_jP1.setLayout(Panel_jP1Layout);
        Panel_jP1Layout.setHorizontalGroup(
            Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refresh_jP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP1)
                .addContainerGap())
        );
        Panel_jP1Layout.setVerticalGroup(
            Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP1)
                    .addComponent(Refresh_jP1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP1Layout = new javax.swing.GroupLayout(jP1);
        jP1.setLayout(jP1Layout);
        jP1Layout.setHorizontalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addComponent(Title_combobox_jP1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rpilist_jP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP1Layout.setVerticalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_combobox_jP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rpilist_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(Panel_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP1, "panelOne");

        jP2.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP2.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP2.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP2.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP2.setText("Zaloguj się do urządzenia.");
        Title_jP2.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP2.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP2.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP2.setText("Podaj nazwę użytkownika oraz hasło.");
        Subtitle_jP2.setPreferredSize(new java.awt.Dimension(503, 24));

        username_title_jP2.setForeground(new java.awt.Color(149, 152, 154));
        username_title_jP2.setText("Nazwa użytkownika:");

        password_title_jP2.setForeground(new java.awt.Color(149, 152, 154));
        password_title_jP2.setText("Hasło:");

        Panel_jP2.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP2.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP2.setPreferredSize(new java.awt.Dimension(88, 59));

        Next_jP2.setText("Dalej");
        Next_jP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP2ActionPerformed(evt);
            }
        });

        Back_jP2.setText("Wstecz");
        Back_jP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP2Layout = new javax.swing.GroupLayout(Panel_jP2);
        Panel_jP2.setLayout(Panel_jP2Layout);
        Panel_jP2Layout.setHorizontalGroup(
            Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP2)
                .addContainerGap())
        );
        Panel_jP2Layout.setVerticalGroup(
            Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP2)
                    .addComponent(Back_jP2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP2Layout = new javax.swing.GroupLayout(jP2);
        jP2.setLayout(jP2Layout);
        jP2Layout.setHorizontalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(username_jP2)
                    .addGroup(jP2Layout.createSequentialGroup()
                        .addGroup(jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_title_jP2)
                            .addComponent(password_title_jP2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(password_jP2))
                .addContainerGap())
        );
        jP2Layout.setVerticalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username_title_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_title_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(Panel_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP2, "panelTwo");

        jP3.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP3.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP3.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP3.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP3.setText("Dodaj plik.");
        Title_jP3.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP3.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP3.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP3.setText("Chcesz stworzyć czy dodać gotowy plik?");
        Subtitle_jP3.setPreferredSize(new java.awt.Dimension(503, 24));

        create_jP3.setText("Stwórz plik");
        create_jP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_jP3ActionPerformed(evt);
            }
        });

        send_jP3.setText("Prześlij plik");
        send_jP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_jP3ActionPerformed(evt);
            }
        });

        Panel_jP3.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP3.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP3.setPreferredSize(new java.awt.Dimension(88, 59));

        Back_jP3.setText("Wstecz");
        Back_jP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP3Layout = new javax.swing.GroupLayout(Panel_jP3);
        Panel_jP3.setLayout(Panel_jP3Layout);
        Panel_jP3Layout.setHorizontalGroup(
            Panel_jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_jP3Layout.setVerticalGroup(
            Panel_jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(Back_jP3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP3Layout = new javax.swing.GroupLayout(jP3);
        jP3.setLayout(jP3Layout);
        jP3Layout.setHorizontalGroup(
            jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(jP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP3Layout.createSequentialGroup()
                        .addComponent(create_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(send_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jP3Layout.setVerticalGroup(
            jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP3, "panelThree");

        jP4_create.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP4.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP4.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP4.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP4.setText("Stwórz plik.");
        Title_jP4.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP4.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP4.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP4.setText("Wybierz schemat i wprowadź tekst.");
        Subtitle_jP4.setPreferredSize(new java.awt.Dimension(503, 24));

        Panel_jP4.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP4.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP4.setPreferredSize(new java.awt.Dimension(88, 59));

        Next_jP4.setText("Dalej");
        Next_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP4ActionPerformed(evt);
            }
        });

        Back_jP4.setText("Wstecz");
        Back_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP4Layout = new javax.swing.GroupLayout(Panel_jP4);
        Panel_jP4.setLayout(Panel_jP4Layout);
        Panel_jP4Layout.setHorizontalGroup(
            Panel_jP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP4)
                .addContainerGap())
        );
        Panel_jP4Layout.setVerticalGroup(
            Panel_jP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP4)
                    .addComponent(Back_jP4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP4_createLayout = new javax.swing.GroupLayout(jP4_create);
        jP4_create.setLayout(jP4_createLayout);
        jP4_createLayout.setHorizontalGroup(
            jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(jP4_createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP4_createLayout.setVerticalGroup(
            jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP4_createLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211)
                .addComponent(Panel_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP4_create, "panelFour");

        jP5_send.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP5.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP5.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP5.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP5.setText("Prześlij plik.");
        Title_jP5.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP5.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP5.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP5.setText("Wybierz plik który chcesz przesłać.");
        Subtitle_jP5.setPreferredSize(new java.awt.Dimension(503, 24));

        select_file_jP5.setText("Wybierz plik");
        select_file_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_file_jP5ActionPerformed(evt);
            }
        });

        file_path_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_path_jP5ActionPerformed(evt);
            }
        });

        Panel_jP5.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP5.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP5.setPreferredSize(new java.awt.Dimension(88, 59));

        Next_jP5.setText("Dalej");
        Next_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP5ActionPerformed(evt);
            }
        });

        Back_jP5.setText("Wstecz");
        Back_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP5ActionPerformed(evt);
            }
        });

        send_button_jP5.setText("Prześlij plik");
        send_button_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_button_jP5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP5Layout = new javax.swing.GroupLayout(Panel_jP5);
        Panel_jP5.setLayout(Panel_jP5Layout);
        Panel_jP5Layout.setHorizontalGroup(
            Panel_jP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(send_button_jP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Next_jP5)
                .addContainerGap())
        );
        Panel_jP5Layout.setVerticalGroup(
            Panel_jP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP5)
                    .addComponent(Back_jP5)
                    .addComponent(send_button_jP5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP5_sendLayout = new javax.swing.GroupLayout(jP5_send);
        jP5_send.setLayout(jP5_sendLayout);
        jP5_sendLayout.setHorizontalGroup(
            jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP5, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(jP5_sendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP5_sendLayout.createSequentialGroup()
                        .addComponent(file_path_jP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_file_jP5)))
                .addContainerGap())
        );
        jP5_sendLayout.setVerticalGroup(
            jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP5_sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_file_jP5)
                    .addComponent(file_path_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170)
                .addComponent(Panel_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP5_send, "panelFive");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rpilist_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpilist_jP1ActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_rpilist_jP1ActionPerformed

    private void Back_jP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelOne");
    }//GEN-LAST:event_Back_jP2ActionPerformed

    private void Next_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelTwo");
        
        full_get_selected = (String)rpilist_jP1.getSelectedItem();
        String[] parts = full_get_selected.split(" ");
        ip_addr_glob = parts[5].substring(0,parts[5].length()-1);
        System.out.println(ip_addr_glob);
        
        
    }//GEN-LAST:event_Next_jP1ActionPerformed

    private void Refresh_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_jP1ActionPerformed
        // TODO add your handling code here:
        rpilist_jP1.removeAllItems();

        int timeout=100;
        int port = 1234;
        String ip_addr = "";
        
        Set<String> HostAddresses = new HashSet<>();
            try {
                for (NetworkInterface ni : Collections.list(NetworkInterface.getNetworkInterfaces())) {
                    if (!ni.isLoopback() && ni.isUp() && ni.getHardwareAddress() != null) {
                        for (InterfaceAddress ia : ni.getInterfaceAddresses()) {
                            if (ia.getBroadcast() != null) {  //If limited to IPV4
                                HostAddresses.add(ia.getAddress().getHostAddress());
                                ip_addr = HostAddresses.toString();
                                System.out.println(ip_addr);
                            }
                        }
                    }
                }
            } catch (SocketException e) { }
        
        try {
            int index = ip_addr.indexOf(" ");
            String firststring = ip_addr.substring(0, index);
            System.out.println(firststring);
            
            firststring = firststring.substring(1);
            String subnet = getSubnet(firststring);
            System.out.println("subnet: " + subnet);
            
            for (int i=1;i<254;i++){

                String host = subnet + i;
                System.out.println("Checking :" + host);

                if (InetAddress.getByName(host).isReachable(timeout)){
                    System.out.println(host + " is reachable");
                    try {
                        Socket connected = new Socket(subnet, port);
                    }
                    catch (Exception s) {
                        System.out.println(s);
                    }
                }
            }
        }
        catch(Exception e){
            System.out.println(e);
        }


        Runtime rt_arp = Runtime.getRuntime();
        //System.out.println("Twoje Raspberry PI w sieci: ");
        String[] cmd_arp = { "/bin/bash", "-c", "arp -a | grep 'b8:27:eb'" };

        Process proc_arp = null;
        try {
            proc_arp = rt_arp.exec(cmd_arp);
        } catch (IOException ex) {
            Logger.getLogger(appframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader is_arp = new BufferedReader(new InputStreamReader(proc_arp.getInputStream()));
        String line_arp;
        try {
            while ((line_arp = is_arp.readLine()) != null) {
                String[] parts = line_arp.split(" ");
                System.out.println("Nazwa urządzenia: " + parts[0] + ", adress ip: " + parts[1].substring(1, parts[1].length()-1) + ", adress mac: "+ parts[3]);
                rpilist_jP1.addItem("Nazwa urządzenia: " + parts[0] + ", adress ip: " + parts[1].substring(1, parts[1].length()-1) + ", adress mac: "+ parts[3]);
            }
              } catch (IOException ex) {
            Logger.getLogger(appframe.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Refresh_jP1ActionPerformed

    private void Next_jP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP2ActionPerformed
        // TODO add your handling code here:
        USER = username_jP2.getText();
        PASS = new String(password_jP2.getPassword());
        
        System.out.println(USER + " " + PASS);
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");
        
    }//GEN-LAST:event_Next_jP2ActionPerformed

    private void Back_jP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelTwo");
    }//GEN-LAST:event_Back_jP3ActionPerformed

    private void Next_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Next_jP4ActionPerformed

    private void Back_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP4ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");
    }//GEN-LAST:event_Back_jP4ActionPerformed

    private void Next_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Next_jP5ActionPerformed

    private void Back_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP5ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");        
    }//GEN-LAST:event_Back_jP5ActionPerformed

    private void create_jP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_jP3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelFour");
    }//GEN-LAST:event_create_jP3ActionPerformed

    private void send_jP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_jP3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelFive");
    }//GEN-LAST:event_send_jP3ActionPerformed

    private void select_file_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_file_jP5ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          System.out.println(selectedFile.getName());
          file_path_glob = fileChooser.getSelectedFile().getAbsolutePath();
          file_path_jP5.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_select_file_jP5ActionPerformed

    private void file_path_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_path_jP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_path_jP5ActionPerformed

    private void send_button_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_button_jP5ActionPerformed
        Session session = null;
        Channel channel = null;
        ChannelSftp channelSftp = null;
        
        try {
            JSch jsch = new JSch();
            session = jsch.getSession(USER, ip_addr_glob, port);
            session.setPassword(PASS);
            java.util.Properties config = new java.util.Properties();
            config.put("StrictHostKeyChecking", "no");
            session.setConfig(config);
            session.connect();
            channel = session.openChannel("sftp");
            channel.connect();
            channelSftp = (ChannelSftp) channel;
            channelSftp.cd("/home/pi/Pictures");
            File f = new File(file_path_glob);
            channelSftp.put(new FileInputStream(f), f.getName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
  
    }//GEN-LAST:event_send_button_jP5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appframe().setVisible(true);
            }
        });
    }

    public static String getSubnet(String ip_addr) {
        int firstSeparator = ip_addr.lastIndexOf("/");
        int lastSeparator = ip_addr.lastIndexOf(".");
        return ip_addr.substring(firstSeparator+1, lastSeparator+1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_jP2;
    private javax.swing.JButton Back_jP3;
    private javax.swing.JButton Back_jP4;
    private javax.swing.JButton Back_jP5;
    private javax.swing.JButton Next_jP1;
    private javax.swing.JButton Next_jP2;
    private javax.swing.JButton Next_jP4;
    private javax.swing.JButton Next_jP5;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel Panel_jP1;
    private javax.swing.JPanel Panel_jP2;
    private javax.swing.JPanel Panel_jP3;
    private javax.swing.JPanel Panel_jP4;
    private javax.swing.JPanel Panel_jP5;
    private javax.swing.JButton Refresh_jP1;
    private javax.swing.JLabel Subtitle_jP1;
    private javax.swing.JLabel Subtitle_jP2;
    private javax.swing.JLabel Subtitle_jP3;
    private javax.swing.JLabel Subtitle_jP4;
    private javax.swing.JLabel Subtitle_jP5;
    private javax.swing.JLabel Title_combobox_jP1;
    private javax.swing.JLabel Title_jP1;
    private javax.swing.JLabel Title_jP2;
    private javax.swing.JLabel Title_jP3;
    private javax.swing.JLabel Title_jP4;
    private javax.swing.JLabel Title_jP5;
    private javax.swing.JButton create_jP3;
    private javax.swing.JTextField file_path_jP5;
    private javax.swing.JPanel jP1;
    private javax.swing.JPanel jP2;
    private javax.swing.JPanel jP3;
    private javax.swing.JPanel jP4_create;
    private javax.swing.JPanel jP5_send;
    private javax.swing.JPasswordField password_jP2;
    private javax.swing.JLabel password_title_jP2;
    private javax.swing.JComboBox<String> rpilist_jP1;
    private javax.swing.JButton select_file_jP5;
    private javax.swing.JButton send_button_jP5;
    private javax.swing.JButton send_jP3;
    private javax.swing.JTextField username_jP2;
    private javax.swing.JLabel username_title_jP2;
    // End of variables declaration//GEN-END:variables
}
