/*

Created by Adrian Rupala 2017

*/

package app_alfa;

import com.jcraft.jsch.*;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.net.Socket;
import java.net.SocketException;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFileChooser;

public class appframe extends javax.swing.JFrame {

    public static String komenda = "";
    public static String USER = "";
    public static String PASS = "";
    public static String host = "";
    public static String ip_route = "";
    public static String full_get_selected = "";
    public static String ip_addr_glob = "";
    public static String file_path_glob = "";
    public static String user_name_global = "";
    public static String user_password_global = "";
    public static String gdrive_auth = "";
    
    public static int port = 22;

    /**
     * Creates new form appframe
     */
    
    public appframe() {
        setTitle("");
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.JPanel();
        jP1 = new javax.swing.JPanel();
        Title_jP1 = new javax.swing.JLabel();
        Subtitle_jP1 = new javax.swing.JLabel();
        Title_combobox_jP1 = new javax.swing.JLabel();
        rpilist_jP1 = new javax.swing.JComboBox<>();
        Panel_jP1 = new javax.swing.JPanel();
        Refresh_jP1 = new javax.swing.JButton();
        Next_jP1 = new javax.swing.JButton();
        jP2 = new javax.swing.JPanel();
        Title_jP2 = new javax.swing.JLabel();
        Subtitle_jP2 = new javax.swing.JLabel();
        username_title_jP2 = new javax.swing.JLabel();
        username_jP2 = new javax.swing.JTextField();
        password_title_jP2 = new javax.swing.JLabel();
        password_jP2 = new javax.swing.JPasswordField();
        Panel_jP2 = new javax.swing.JPanel();
        Next_jP2 = new javax.swing.JButton();
        Back_jP2 = new javax.swing.JButton();
        jP3_choose = new javax.swing.JPanel();
        Title_jP8 = new javax.swing.JLabel();
        Subtitle_jP6 = new javax.swing.JLabel();
        create_jP4 = new javax.swing.JButton();
        send_jP4 = new javax.swing.JButton();
        Panel_jP8 = new javax.swing.JPanel();
        Back_jP8 = new javax.swing.JButton();
        Settings_jP4 = new javax.swing.JButton();
        jP3 = new javax.swing.JPanel();
        Title_jP3 = new javax.swing.JLabel();
        Subtitle_jP3 = new javax.swing.JLabel();
        gdrive_sync_jP3 = new javax.swing.JButton();
        local_storage_jP3 = new javax.swing.JButton();
        Panel_jP3 = new javax.swing.JPanel();
        Back_jP3 = new javax.swing.JButton();
        jP4_create = new javax.swing.JPanel();
        Title_jP4 = new javax.swing.JLabel();
        Subtitle_jP4 = new javax.swing.JLabel();
        file_path_jP4 = new javax.swing.JTextField();
        select_file_jP4 = new javax.swing.JButton();
        Panel_jP4 = new javax.swing.JPanel();
        Next_jP4 = new javax.swing.JButton();
        Back_jP4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jP5_send = new javax.swing.JPanel();
        Title_jP5 = new javax.swing.JLabel();
        Subtitle_jP5 = new javax.swing.JLabel();
        select_file_jP5 = new javax.swing.JButton();
        file_path_jP5 = new javax.swing.JTextField();
        Panel_jP5 = new javax.swing.JPanel();
        Next_jP5 = new javax.swing.JButton();
        Back_jP5 = new javax.swing.JButton();
        send_button_jP5 = new javax.swing.JButton();
        jP6_settings = new javax.swing.JPanel();
        Title_jP6 = new javax.swing.JLabel();
        start_system_jP6 = new javax.swing.JButton();
        off_system_jP6 = new javax.swing.JButton();
        restart_device_jP6 = new javax.swing.JButton();
        add_user_jP6 = new javax.swing.JButton();
        google_auth_jP6 = new javax.swing.JButton();
        Panel_jP6 = new javax.swing.JPanel();
        Back_jP6 = new javax.swing.JButton();
        jP7_add_user = new javax.swing.JPanel();
        Title_jP7 = new javax.swing.JLabel();
        Subtitle_jP7 = new javax.swing.JLabel();
        user_label_jP7 = new javax.swing.JLabel();
        user_jP7 = new javax.swing.JTextField();
        password_label_jP7 = new javax.swing.JLabel();
        password_jP7 = new javax.swing.JPasswordField();
        Panel_jP7 = new javax.swing.JPanel();
        Back_jP7 = new javax.swing.JButton();
        add_user_button_jP7 = new javax.swing.JButton();
        jP8_gdrive = new javax.swing.JPanel();
        Title_jP9 = new javax.swing.JLabel();
        Subtitle_jP9 = new javax.swing.JLabel();
        info_text1_jP9 = new javax.swing.JLabel();
        website_button_jP9 = new javax.swing.JButton();
        info_text2_jP9 = new javax.swing.JLabel();
        get_auth_code_jP9 = new javax.swing.JTextField();
        Panel_jP9 = new javax.swing.JPanel();
        Back_jP9 = new javax.swing.JButton();
        auth_button_jP9 = new javax.swing.JButton();
        create_picture_jP9 = new javax.swing.JButton();
        info_text2_jP10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P1.setLayout(new java.awt.CardLayout());

        jP1.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP1.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP1.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP1.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP1.setText("Witaj!");
        Title_jP1.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP1.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP1.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP1.setText("Aby kontynuować wybierz swoje urządzenie z listy poniżej...");
        Subtitle_jP1.setPreferredSize(new java.awt.Dimension(503, 24));

        Title_combobox_jP1.setForeground(new java.awt.Color(149, 152, 154));
        Title_combobox_jP1.setText("Urządzenia podłączone do sieci...");

        rpilist_jP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Przed użyciem odśwież listę urządzeń" }));
        rpilist_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpilist_jP1ActionPerformed(evt);
            }
        });

        Panel_jP1.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP1.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP1.setPreferredSize(new java.awt.Dimension(88, 59));

        Refresh_jP1.setText("Odśwież listę");
        Refresh_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_jP1ActionPerformed(evt);
            }
        });

        Next_jP1.setText("Dalej");
        Next_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP1Layout = new javax.swing.GroupLayout(Panel_jP1);
        Panel_jP1.setLayout(Panel_jP1Layout);
        Panel_jP1Layout.setHorizontalGroup(
            Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refresh_jP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP1)
                .addContainerGap())
        );
        Panel_jP1Layout.setVerticalGroup(
            Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP1)
                    .addComponent(Refresh_jP1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP1Layout = new javax.swing.GroupLayout(jP1);
        jP1.setLayout(jP1Layout);
        jP1Layout.setHorizontalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addComponent(Title_combobox_jP1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rpilist_jP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP1Layout.setVerticalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_combobox_jP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rpilist_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(Panel_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP1, "panelOne");

        jP2.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP2.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP2.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP2.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP2.setText("Zaloguj się do urządzenia.");
        Title_jP2.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP2.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP2.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP2.setText("Podaj nazwę użytkownika oraz hasło.");
        Subtitle_jP2.setPreferredSize(new java.awt.Dimension(503, 24));

        username_title_jP2.setForeground(new java.awt.Color(149, 152, 154));
        username_title_jP2.setText("Nazwa użytkownika:");

        password_title_jP2.setForeground(new java.awt.Color(149, 152, 154));
        password_title_jP2.setText("Hasło:");

        Panel_jP2.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP2.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP2.setPreferredSize(new java.awt.Dimension(88, 59));

        Next_jP2.setText("Dalej");
        Next_jP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP2ActionPerformed(evt);
            }
        });

        Back_jP2.setText("Wstecz");
        Back_jP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP2Layout = new javax.swing.GroupLayout(Panel_jP2);
        Panel_jP2.setLayout(Panel_jP2Layout);
        Panel_jP2Layout.setHorizontalGroup(
            Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP2)
                .addContainerGap())
        );
        Panel_jP2Layout.setVerticalGroup(
            Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP2)
                    .addComponent(Back_jP2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP2Layout = new javax.swing.GroupLayout(jP2);
        jP2.setLayout(jP2Layout);
        jP2Layout.setHorizontalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(username_jP2)
                    .addGroup(jP2Layout.createSequentialGroup()
                        .addGroup(jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_title_jP2)
                            .addComponent(password_title_jP2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(password_jP2))
                .addContainerGap())
        );
        jP2Layout.setVerticalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username_title_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_title_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(Panel_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP2, "panelTwo");

        jP3_choose.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP8.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP8.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP8.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP8.setText("Dodaj plik.");
        Title_jP8.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP6.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP6.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP6.setText("Chcesz stworzyć czy dodać gotowy plik?");
        Subtitle_jP6.setPreferredSize(new java.awt.Dimension(503, 24));

        create_jP4.setText("Stwórz plik");
        create_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_jP4ActionPerformed(evt);
            }
        });

        send_jP4.setText("Prześlij plik");
        send_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_jP4ActionPerformed(evt);
            }
        });

        Panel_jP8.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP8.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP8.setPreferredSize(new java.awt.Dimension(88, 59));

        Back_jP8.setText("Wstecz");
        Back_jP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP8ActionPerformed(evt);
            }
        });

        Settings_jP4.setText("Ustawienia systemu");
        Settings_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Settings_jP4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP8Layout = new javax.swing.GroupLayout(Panel_jP8);
        Panel_jP8.setLayout(Panel_jP8Layout);
        Panel_jP8Layout.setHorizontalGroup(
            Panel_jP8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Settings_jP4)
                .addContainerGap())
        );
        Panel_jP8Layout.setVerticalGroup(
            Panel_jP8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_jP8)
                    .addComponent(Settings_jP4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP3_chooseLayout = new javax.swing.GroupLayout(jP3_choose);
        jP3_choose.setLayout(jP3_chooseLayout);
        jP3_chooseLayout.setHorizontalGroup(
            jP3_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP8, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP3_chooseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP3_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP3_chooseLayout.createSequentialGroup()
                        .addComponent(create_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(send_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jP3_chooseLayout.setVerticalGroup(
            jP3_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP3_chooseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP3_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(create_jP4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(send_jP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Panel_jP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP3_choose, "panelInactve1");

        jP3.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP3.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP3.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP3.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP3.setText("Wybierz opcję synchronizacji.");
        Title_jP3.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP3.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP3.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP3.setText("Wolisz używać chmury czy lokalnego dysku?");
        Subtitle_jP3.setPreferredSize(new java.awt.Dimension(503, 24));

        gdrive_sync_jP3.setText("Chrmura Google");
        gdrive_sync_jP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdrive_sync_jP3ActionPerformed(evt);
            }
        });

        local_storage_jP3.setText("Przestrzeń lokalna");
        local_storage_jP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                local_storage_jP3ActionPerformed(evt);
            }
        });

        Panel_jP3.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP3.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP3.setPreferredSize(new java.awt.Dimension(88, 59));

        Back_jP3.setText("Wstecz");
        Back_jP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP3Layout = new javax.swing.GroupLayout(Panel_jP3);
        Panel_jP3.setLayout(Panel_jP3Layout);
        Panel_jP3Layout.setHorizontalGroup(
            Panel_jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP3)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        Panel_jP3Layout.setVerticalGroup(
            Panel_jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(Back_jP3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP3Layout = new javax.swing.GroupLayout(jP3);
        jP3.setLayout(jP3Layout);
        jP3Layout.setHorizontalGroup(
            jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP3Layout.createSequentialGroup()
                        .addComponent(gdrive_sync_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(local_storage_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(Panel_jP3, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
        jP3Layout.setVerticalGroup(
            jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gdrive_sync_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(local_storage_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Panel_jP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP3, "panelThree");

        jP4_create.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP4.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP4.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP4.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP4.setText("Stwórz obraz.");
        Title_jP4.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP4.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP4.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP4.setText("Wybierz schemat i wprowadź tekst.");
        Subtitle_jP4.setPreferredSize(new java.awt.Dimension(503, 24));

        file_path_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_path_jP4ActionPerformed(evt);
            }
        });

        select_file_jP4.setText("Wybierz plik");
        select_file_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_file_jP4ActionPerformed(evt);
            }
        });

        Panel_jP4.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP4.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP4.setPreferredSize(new java.awt.Dimension(88, 59));

        Next_jP4.setText("Dalej");
        Next_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP4ActionPerformed(evt);
            }
        });

        Back_jP4.setText("Wstecz");
        Back_jP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP4Layout = new javax.swing.GroupLayout(Panel_jP4);
        Panel_jP4.setLayout(Panel_jP4Layout);
        Panel_jP4Layout.setHorizontalGroup(
            Panel_jP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP4)
                .addContainerGap())
        );
        Panel_jP4Layout.setVerticalGroup(
            Panel_jP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP4)
                    .addComponent(Back_jP4))
                .addContainerGap())
        );

        jLabel1.setForeground(new java.awt.Color(149, 152, 154));
        jLabel1.setText("Wybierz szablon pliku.");

        jLabel2.setForeground(new java.awt.Color(149, 152, 154));
        jLabel2.setText("Wprowadź nagłówek.");

        jLabel3.setForeground(new java.awt.Color(149, 152, 154));
        jLabel3.setText("Wprowadź treść.");

        jLabel4.setForeground(new java.awt.Color(149, 152, 154));
        jLabel4.setText("Wybierz obraz.");

        jButton1.setText("Wybierz plik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP4_createLayout = new javax.swing.GroupLayout(jP4_create);
        jP4_create.setLayout(jP4_createLayout);
        jP4_createLayout.setHorizontalGroup(
            jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP4, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP4_createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(Title_jP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addGroup(jP4_createLayout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jP4_createLayout.createSequentialGroup()
                        .addGroup(jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP4_createLayout.createSequentialGroup()
                                .addComponent(file_path_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(select_file_jP4))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP4_createLayout.setVerticalGroup(
            jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP4_createLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_file_jP4)
                    .addComponent(file_path_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP4_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(1, 1, 1)
                .addComponent(Panel_jP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP4_create, "panelFour");

        jP5_send.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP5.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP5.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP5.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP5.setText("Prześlij plik.");
        Title_jP5.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP5.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP5.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP5.setText("Wybierz plik który chcesz przesłać.");
        Subtitle_jP5.setPreferredSize(new java.awt.Dimension(503, 24));

        select_file_jP5.setText("Wybierz plik");
        select_file_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_file_jP5ActionPerformed(evt);
            }
        });

        file_path_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_path_jP5ActionPerformed(evt);
            }
        });

        Panel_jP5.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP5.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP5.setPreferredSize(new java.awt.Dimension(88, 59));

        Next_jP5.setText("Dalej");
        Next_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP5ActionPerformed(evt);
            }
        });

        Back_jP5.setText("Wstecz");
        Back_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP5ActionPerformed(evt);
            }
        });

        send_button_jP5.setText("Prześlij plik");
        send_button_jP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_button_jP5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP5Layout = new javax.swing.GroupLayout(Panel_jP5);
        Panel_jP5.setLayout(Panel_jP5Layout);
        Panel_jP5Layout.setHorizontalGroup(
            Panel_jP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(send_button_jP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Next_jP5)
                .addContainerGap())
        );
        Panel_jP5Layout.setVerticalGroup(
            Panel_jP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP5)
                    .addComponent(Back_jP5)
                    .addComponent(send_button_jP5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP5_sendLayout = new javax.swing.GroupLayout(jP5_send);
        jP5_send.setLayout(jP5_sendLayout);
        jP5_sendLayout.setHorizontalGroup(
            jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP5, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP5_sendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP5_sendLayout.createSequentialGroup()
                        .addComponent(file_path_jP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_file_jP5)))
                .addContainerGap())
        );
        jP5_sendLayout.setVerticalGroup(
            jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP5_sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP5_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_file_jP5)
                    .addComponent(file_path_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182)
                .addComponent(Panel_jP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP5_send, "panelFive");

        jP6_settings.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP6.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP6.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP6.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP6.setText("Ustawienia systemu.");
        Title_jP6.setPreferredSize(new java.awt.Dimension(54, 39));

        start_system_jP6.setText("Uruchom system");
        start_system_jP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_system_jP6ActionPerformed(evt);
            }
        });

        off_system_jP6.setText("Wyłącz system");
        off_system_jP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                off_system_jP6ActionPerformed(evt);
            }
        });

        restart_device_jP6.setText("Zrestartuj urządzenie");
        restart_device_jP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_device_jP6ActionPerformed(evt);
            }
        });

        add_user_jP6.setText("Dodaj użytkownika");
        add_user_jP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_jP6ActionPerformed(evt);
            }
        });

        google_auth_jP6.setText("Autoryzacja Dysku Google");
        google_auth_jP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                google_auth_jP6ActionPerformed(evt);
            }
        });

        Panel_jP6.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP6.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP6.setPreferredSize(new java.awt.Dimension(88, 59));

        Back_jP6.setText("Wstecz");
        Back_jP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP6Layout = new javax.swing.GroupLayout(Panel_jP6);
        Panel_jP6.setLayout(Panel_jP6Layout);
        Panel_jP6Layout.setHorizontalGroup(
            Panel_jP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP6)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        Panel_jP6Layout.setVerticalGroup(
            Panel_jP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(Back_jP6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP6_settingsLayout = new javax.swing.GroupLayout(jP6_settings);
        jP6_settings.setLayout(jP6_settingsLayout);
        jP6_settingsLayout.setHorizontalGroup(
            jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP6, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP6_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP6_settingsLayout.createSequentialGroup()
                        .addGroup(jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_user_jP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(start_system_jP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(off_system_jP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(google_auth_jP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restart_device_jP6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP6_settingsLayout.setVerticalGroup(
            jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP6_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restart_device_jP6)
                    .addGroup(jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(start_system_jP6)
                        .addComponent(off_system_jP6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP6_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_user_jP6)
                    .addComponent(google_auth_jP6))
                .addGap(177, 177, 177)
                .addComponent(Panel_jP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP6_settings, "panelSix");

        jP7_add_user.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP7.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP7.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP7.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP7.setText("Dodaj użytkownika.");
        Title_jP7.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP7.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP7.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP7.setText("Podaj nazwę oraz hasło dla nowego użytkownika.");
        Subtitle_jP7.setPreferredSize(new java.awt.Dimension(503, 24));

        user_label_jP7.setFont(new java.awt.Font("SF Pro Text", 0, 10)); // NOI18N
        user_label_jP7.setForeground(new java.awt.Color(149, 152, 154));
        user_label_jP7.setText("Podaj nazwę użytkownika.");

        password_label_jP7.setFont(new java.awt.Font("SF Pro Text", 0, 10)); // NOI18N
        password_label_jP7.setForeground(new java.awt.Color(149, 152, 154));
        password_label_jP7.setText("Podaj hasło.");

        Panel_jP7.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP7.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP7.setPreferredSize(new java.awt.Dimension(88, 59));

        Back_jP7.setText("Wstecz");
        Back_jP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP7ActionPerformed(evt);
            }
        });

        add_user_button_jP7.setText("Dodaj użytkownika");
        add_user_button_jP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_button_jP7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP7Layout = new javax.swing.GroupLayout(Panel_jP7);
        Panel_jP7.setLayout(Panel_jP7Layout);
        Panel_jP7Layout.setHorizontalGroup(
            Panel_jP7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_user_button_jP7))
        );
        Panel_jP7Layout.setVerticalGroup(
            Panel_jP7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_jP7)
                    .addComponent(add_user_button_jP7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP7_add_userLayout = new javax.swing.GroupLayout(jP7_add_user);
        jP7_add_user.setLayout(jP7_add_userLayout);
        jP7_add_userLayout.setHorizontalGroup(
            jP7_add_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP7, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP7_add_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP7_add_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(user_label_jP7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_jP7)
                    .addComponent(password_label_jP7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password_jP7))
                .addContainerGap())
        );
        jP7_add_userLayout.setVerticalGroup(
            jP7_add_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP7_add_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user_label_jP7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_jP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_label_jP7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_jP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(Panel_jP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP7_add_user, "panelSeven");

        jP8_gdrive.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP9.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP9.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP9.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP9.setText("Autoryzacja Google Drive.");
        Title_jP9.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP9.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP9.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP9.setText("Autoryzacja jest potrzebna do synchronizacji plików.");
        Subtitle_jP9.setPreferredSize(new java.awt.Dimension(503, 24));

        info_text1_jP9.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        info_text1_jP9.setForeground(new java.awt.Color(149, 152, 154));
        info_text1_jP9.setText("Kliknij w przycisk po prawej stronie aby przejść do strony autoryzacji.");
        info_text1_jP9.setMaximumSize(new java.awt.Dimension(129, 16));
        info_text1_jP9.setMinimumSize(new java.awt.Dimension(129, 16));
        info_text1_jP9.setPreferredSize(new java.awt.Dimension(129, 16));

        website_button_jP9.setText("Przejdź do strony!");
        website_button_jP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                website_button_jP9ActionPerformed(evt);
            }
        });

        info_text2_jP9.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        info_text2_jP9.setForeground(new java.awt.Color(149, 152, 154));
        info_text2_jP9.setText("Wklej lub przepisz kod który został dla Ciebie wygenerowany.");
        info_text2_jP9.setMaximumSize(new java.awt.Dimension(129, 16));
        info_text2_jP9.setMinimumSize(new java.awt.Dimension(129, 16));
        info_text2_jP9.setPreferredSize(new java.awt.Dimension(129, 16));

        get_auth_code_jP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_auth_code_jP9ActionPerformed(evt);
            }
        });

        Panel_jP9.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP9.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP9.setPreferredSize(new java.awt.Dimension(88, 59));

        Back_jP9.setText("Wstecz");
        Back_jP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP9ActionPerformed(evt);
            }
        });

        auth_button_jP9.setText("Autoryzuj");
        auth_button_jP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auth_button_jP9ActionPerformed(evt);
            }
        });

        create_picture_jP9.setText("Generowanie obrazu");
        create_picture_jP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_picture_jP9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP9Layout = new javax.swing.GroupLayout(Panel_jP9);
        Panel_jP9.setLayout(Panel_jP9Layout);
        Panel_jP9Layout.setHorizontalGroup(
            Panel_jP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_picture_jP9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(auth_button_jP9)
                .addContainerGap())
        );
        Panel_jP9Layout.setVerticalGroup(
            Panel_jP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP9Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_jP9)
                    .addComponent(auth_button_jP9)
                    .addComponent(create_picture_jP9))
                .addContainerGap())
        );

        info_text2_jP10.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        info_text2_jP10.setForeground(new java.awt.Color(149, 152, 154));
        info_text2_jP10.setText("Kolejne pliki będziesz synchronizował za pomocą wrzucania ich na wybrany dysk Google.");
        info_text2_jP10.setMaximumSize(new java.awt.Dimension(129, 16));
        info_text2_jP10.setMinimumSize(new java.awt.Dimension(129, 16));
        info_text2_jP10.setPreferredSize(new java.awt.Dimension(129, 16));

        javax.swing.GroupLayout jP8_gdriveLayout = new javax.swing.GroupLayout(jP8_gdrive);
        jP8_gdrive.setLayout(jP8_gdriveLayout);
        jP8_gdriveLayout.setHorizontalGroup(
            jP8_gdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP9, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(jP8_gdriveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP8_gdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info_text1_jP9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info_text2_jP9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_auth_code_jP9)
                    .addComponent(Subtitle_jP9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(jP8_gdriveLayout.createSequentialGroup()
                        .addComponent(website_button_jP9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(info_text2_jP10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP8_gdriveLayout.setVerticalGroup(
            jP8_gdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP8_gdriveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(info_text1_jP9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website_button_jP9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info_text2_jP9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_auth_code_jP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info_text2_jP10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Panel_jP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP8_gdrive, "panelEight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rpilist_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpilist_jP1ActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_rpilist_jP1ActionPerformed

    private void Back_jP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelOne");
    }//GEN-LAST:event_Back_jP2ActionPerformed

    private void Next_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelTwo");
        
        full_get_selected = (String)rpilist_jP1.getSelectedItem();
        String[] parts = full_get_selected.split(" ");
        ip_addr_glob = parts[5].substring(0,parts[5].length()-1);
        System.out.println(ip_addr_glob);
        
        
    }//GEN-LAST:event_Next_jP1ActionPerformed

    private void Refresh_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_jP1ActionPerformed
        // TODO add your handling code here:
        rpilist_jP1.removeAllItems();

        int timeout=150;
        int port_ping = 1234;
        
        String ip_addr = "";
        
        Set<String> HostAddresses = new HashSet<>();
            try {
                for (NetworkInterface ni : Collections.list(NetworkInterface.getNetworkInterfaces())) {
                    if (!ni.isLoopback() && ni.isUp() && !ni.isVirtual() && ni.getHardwareAddress() != null) {
                        for (InterfaceAddress ia : ni.getInterfaceAddresses()) {
                            if (ia.getBroadcast() != null) {
                                    HostAddresses.add(ia.getAddress().getHostAddress());
                                    ip_addr = HostAddresses.toString();
                                    System.out.println(ip_addr);
                            }
                        }
                    }
                }
            } catch (SocketException e) { }
        
            for (String s : HostAddresses){
                try {
                    int index = ip_addr.indexOf(" ");

                    System.out.println(s);

                    s = s.substring(0);
                    String subnet = getSubnet(s);
                    System.out.println("subnet: " + subnet);

                    for (int i=1;i<254;i++){

                        String host_ip = subnet + i;
                        System.out.println("Checking :" + host_ip);

                            if (InetAddress.getByName(host_ip).isReachable(timeout)){
                                System.out.println(host_ip + " is reachable");
                                try {
                                    Socket connected = new Socket(subnet, port_ping);
                                }
                                catch (IOException x) {
                                    System.out.println(x);
                                }
                            }
                        }
                    }
        catch(IOException e){ }
    }

        Runtime rt_arp = Runtime.getRuntime();
        String[] cmd_arp = { "/bin/bash", "-c", "arp -an | grep 'b8:27:eb'" };

        Process proc_arp = null;
        try {
            proc_arp = rt_arp.exec(cmd_arp);
        } catch (IOException ex) {
            Logger.getLogger(appframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader is_arp = new BufferedReader(new InputStreamReader(proc_arp.getInputStream()));
        String line_arp;
        try {
            while ((line_arp = is_arp.readLine()) != null) {
                String[] parts = line_arp.split(" ");
                System.out.println("Nazwa urządzenia: " + parts[0] + ", adress ip: " + parts[1].substring(1, parts[1].length()-1) + ", adress mac: "+ parts[3]);
                rpilist_jP1.addItem("Nazwa urządzenia: " + parts[0] + ", adress ip: " + parts[1].substring(1, parts[1].length()-1) + ", adress mac: "+ parts[3]);
            }
              } catch (IOException ex) {
            Logger.getLogger(appframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Refresh_jP1ActionPerformed

    private void Next_jP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP2ActionPerformed
        // TODO add your handling code here:
        USER = username_jP2.getText();
        PASS = new String(password_jP2.getPassword());
        
        System.out.println(USER + " " + PASS);
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");
        
    }//GEN-LAST:event_Next_jP2ActionPerformed

    private void Back_jP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelTwo");
    }//GEN-LAST:event_Back_jP3ActionPerformed

    private void Next_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Next_jP4ActionPerformed

    private void Back_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP4ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");
    }//GEN-LAST:event_Back_jP4ActionPerformed

    private void Next_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Next_jP5ActionPerformed

    private void Back_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP5ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");        
    }//GEN-LAST:event_Back_jP5ActionPerformed

    private void gdrive_sync_jP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdrive_sync_jP3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelEight");
    }//GEN-LAST:event_gdrive_sync_jP3ActionPerformed

    private void local_storage_jP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_local_storage_jP3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelFive");
    }//GEN-LAST:event_local_storage_jP3ActionPerformed

    private void select_file_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_file_jP5ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          System.out.println(selectedFile.getName());
          file_path_glob = fileChooser.getSelectedFile().getAbsolutePath();
          file_path_jP5.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_select_file_jP5ActionPerformed

    private void file_path_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_path_jP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_path_jP5ActionPerformed

    private void send_button_jP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_button_jP5ActionPerformed
        Session session = null;
        Channel channel = null;
        ChannelSftp channelSftp = null;
        
        try {
            JSch jsch = new JSch();
            session = jsch.getSession(USER, ip_addr_glob, port);
            session.setPassword(PASS);
            java.util.Properties config = new java.util.Properties();
            config.put("StrictHostKeyChecking", "no");
            session.setConfig(config);
            session.connect();
            channel = session.openChannel("sftp");
            channel.connect();
            channelSftp = (ChannelSftp) channel;
            channelSftp.cd("/home/pi/Pictures");
            File f = new File(file_path_glob);
            channelSftp.put(new FileInputStream(f), f.getName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
  
    }//GEN-LAST:event_send_button_jP5ActionPerformed

    private void Back_jP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP6ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");
    }//GEN-LAST:event_Back_jP6ActionPerformed

    private void start_system_jP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_system_jP6ActionPerformed
        // TODO add your handling code here:
        komenda = "cd ~/ && screen -dm bash -c '/home/pi/Server_wyswietlania/DisplayMode.sh'";        
        
        try
        {
            JSch jsch = new JSch();

            Session session = jsch.getSession(USER, host, port);
            session.setConfig("StrictHostKeyChecking", "no");
            session.setPassword(PASS);
            session.connect();

            String command = komenda;
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command);

            channel.setInputStream(null);

            ((ChannelExec) channel).setErrStream(System.err);

            InputStream in = channel.getInputStream();

            channel.connect();
            StringBuilder sb = new StringBuilder();
            byte[] tmp = new byte[1024];
            while (true)
            {
                while (in.available() > 0)
                {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0)
                        break;
                    sb.append(new String(tmp, 0, i));
                }
                if (channel.isClosed())
                {
                    if (in.available() > 0)
                        continue;
                    //System.out.println("exit-status: "
                    //        + channel.getExitStatus());
                    break;
                }
                try
                {
                    Thread.sleep(500);
                }
                catch (Exception ee)
                {
                }
            }
            //disconnecting and closing
            channel.disconnect();

            session.disconnect();
            System.out.println("System został uruchomiony bez błędu.");
            System.out.println(sb.toString());
        }
        catch (Exception e)
        {
             //something should be done here
            e.printStackTrace();

        }        
    }//GEN-LAST:event_start_system_jP6ActionPerformed

    private void restart_device_jP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_device_jP6ActionPerformed
        // TODO add your handling code here:
        komenda = "sudo reboot now";
        
        try
        {
            JSch jsch = new JSch();

            Session session = jsch.getSession(USER, host, port);
            session.setConfig("StrictHostKeyChecking", "no");
            session.setPassword(PASS);
            session.connect();

            String command = komenda;
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command);

            channel.setInputStream(null);

            ((ChannelExec) channel).setErrStream(System.err);

            InputStream in = channel.getInputStream();

            channel.connect();
            StringBuilder sb = new StringBuilder();
            byte[] tmp = new byte[1024];
            while (true)
            {
                while (in.available() > 0)
                {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0)
                        break;
                    sb.append(new String(tmp, 0, i));
                }
                if (channel.isClosed())
                {
                    if (in.available() > 0)
                        continue;
                    //System.out.println("exit-status: "
                    //        + channel.getExitStatus());
                    break;
                }
                try
                {
                    Thread.sleep(500);
                }
                catch (Exception ee)
                {
                }
            }
            //disconnecting and closing
            channel.disconnect();

            session.disconnect();
            System.out.println("Restart serwera powiódł się.");
            System.out.println(sb.toString());
        }
        catch (Exception e)
        {
             //something should be done here
            e.printStackTrace();
        }       
        
    }//GEN-LAST:event_restart_device_jP6ActionPerformed

    private void off_system_jP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_off_system_jP6ActionPerformed
        // TODO add your handling code here:
        
        komenda = "pkill -f 'SCREEN -dm bash -c' && pkill -f 'java -jar'";
        
        try
        {
            JSch jsch = new JSch();

            Session session = jsch.getSession(USER, host, port);
            session.setConfig("StrictHostKeyChecking", "no");
            session.setPassword(PASS);
            session.connect();

            String command = komenda;
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command);

            channel.setInputStream(null);

            ((ChannelExec) channel).setErrStream(System.err);

            InputStream in = channel.getInputStream();

            channel.connect();
            StringBuilder sb = new StringBuilder();
            byte[] tmp = new byte[1024];
            while (true)
            {
                while (in.available() > 0)
                {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0)
                        break;
                    sb.append(new String(tmp, 0, i));
                }
                if (channel.isClosed())
                {
                    if (in.available() > 0)
                        continue;
                    //System.out.println("exit-status: "
                    //        + channel.getExitStatus());
                    break;
                }
                try
                {
                    Thread.sleep(500);
                }
                catch (Exception ee)
                {
                }
            }
            //disconnecting and closing
            channel.disconnect();

            session.disconnect();
            System.out.println("System został wyłączony poprawnie.");
            System.out.println(sb.toString());
        }
        catch (Exception e)
        {
             //something should be done here
            e.printStackTrace();

        }       
        
    }//GEN-LAST:event_off_system_jP6ActionPerformed

    private void Back_jP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP7ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelSix");        
    }//GEN-LAST:event_Back_jP7ActionPerformed

    private void add_user_jP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_jP6ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelSeven");
    }//GEN-LAST:event_add_user_jP6ActionPerformed

    private void add_user_button_jP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_button_jP7ActionPerformed
        // TODO add your handling code here:
        user_name_global = user_jP7.getText();
        user_password_global = new String(password_jP7.getPassword());

        komenda = "pkill -f 'SCREEN -dm bash -c' && /home/pi/add_user.sh'" + user_name_global + user_password_global;
        
        try
        {
            JSch jsch = new JSch();

            Session session = jsch.getSession(USER, host, port);
            session.setConfig("StrictHostKeyChecking", "no");
            session.setPassword(PASS);
            session.connect();

            String command = komenda;
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command);

            channel.setInputStream(null);

            ((ChannelExec) channel).setErrStream(System.err);

            InputStream in = channel.getInputStream();

            channel.connect();
            StringBuilder sb = new StringBuilder();
            byte[] tmp = new byte[1024];
            while (true)
            {
                while (in.available() > 0)
                {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0)
                        break;
                    sb.append(new String(tmp, 0, i));
                }
                if (channel.isClosed())
                {
                    if (in.available() > 0)
                        continue;
                    //System.out.println("exit-status: "
                    //        + channel.getExitStatus());
                    break;
                }
                try
                {
                    Thread.sleep(500);
                }
                catch (Exception ee)
                {
                }
            }
            //disconnecting and closing
            channel.disconnect();

            session.disconnect();
            System.out.println("System został wyłączony poprawnie.");
            System.out.println(sb.toString());
        }
        catch (Exception e)
        {
             //something should be done here
            e.printStackTrace();

        }       

    }//GEN-LAST:event_add_user_button_jP7ActionPerformed

    private void Back_jP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP9ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelThree");        
    }//GEN-LAST:event_Back_jP9ActionPerformed

    private void website_button_jP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_website_button_jP9ActionPerformed
        // TODO add your handling code here:
        try { 
         String url = "https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=1056816309698.apps.googleusercontent.com&access_type=offline";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }        
    }//GEN-LAST:event_website_button_jP9ActionPerformed

    private void google_auth_jP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_google_auth_jP6ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelEight");
        
    }//GEN-LAST:event_google_auth_jP6ActionPerformed

    private void get_auth_code_jP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_auth_code_jP9ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_get_auth_code_jP9ActionPerformed

    private void auth_button_jP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auth_button_jP9ActionPerformed
        // TODO add your handling code here:
        gdrive_auth = get_auth_code_jP9.getText();
        
        komenda = "gdfstool auth -a /home/pi/Serwer_wyswietlania/gdfs.creds '"+gdrive_auth+"'";     
        System.out.println(komenda);

        try
        {
            JSch jsch = new JSch();
            Session session = jsch.getSession(USER, ip_addr_glob, port);
            session.setConfig("StrictHostKeyChecking", "no");
            session.setPassword(PASS);
            session.connect();

            String command = komenda;
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command);

            channel.setInputStream(null);

            ((ChannelExec) channel).setErrStream(System.err);

            InputStream in = channel.getInputStream();

            channel.connect();
            StringBuilder sb = new StringBuilder();
            byte[] tmp = new byte[1024];
            while (true)
            {
                while (in.available() > 0)
                {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0)
                        break;
                    sb.append(new String(tmp, 0, i));
                }
                if (channel.isClosed())
                {
                    if (in.available() > 0)
                        continue;
                    //System.out.println("exit-status: "
                    //        + channel.getExitStatus());
                    break;
                }
                try
                {
                    Thread.sleep(500);
                }
                catch (Exception ee)
                {
                }
            }
            //disconnecting and closing
            channel.disconnect();

            session.disconnect();
            System.out.println(sb.toString());
        }
        catch (JSchException | IOException e){ }              
    }//GEN-LAST:event_auth_button_jP9ActionPerformed

    private void create_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_jP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_jP4ActionPerformed

    private void send_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_jP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_jP4ActionPerformed

    private void Back_jP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back_jP8ActionPerformed

    private void Settings_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Settings_jP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Settings_jP4ActionPerformed

    private void file_path_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_path_jP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_path_jP4ActionPerformed

    private void select_file_jP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_file_jP4ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          System.out.println(selectedFile.getName());
          file_path_glob = fileChooser.getSelectedFile().getAbsolutePath();
          file_path_jP4.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }        
    }//GEN-LAST:event_select_file_jP4ActionPerformed

    private void create_picture_jP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_picture_jP9ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelFour");        
    }//GEN-LAST:event_create_picture_jP9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appframe().setVisible(true);
            }
        });
    }

    public static String getSubnet(String firststring) {
        int firstSeparator = firststring.lastIndexOf("/");
        int lastSeparator = firststring.lastIndexOf(".");
        return firststring.substring(firstSeparator+1, lastSeparator+1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_jP2;
    private javax.swing.JButton Back_jP3;
    private javax.swing.JButton Back_jP4;
    private javax.swing.JButton Back_jP5;
    private javax.swing.JButton Back_jP6;
    private javax.swing.JButton Back_jP7;
    private javax.swing.JButton Back_jP8;
    private javax.swing.JButton Back_jP9;
    private javax.swing.JButton Next_jP1;
    private javax.swing.JButton Next_jP2;
    private javax.swing.JButton Next_jP4;
    private javax.swing.JButton Next_jP5;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel Panel_jP1;
    private javax.swing.JPanel Panel_jP2;
    private javax.swing.JPanel Panel_jP3;
    private javax.swing.JPanel Panel_jP4;
    private javax.swing.JPanel Panel_jP5;
    private javax.swing.JPanel Panel_jP6;
    private javax.swing.JPanel Panel_jP7;
    private javax.swing.JPanel Panel_jP8;
    private javax.swing.JPanel Panel_jP9;
    private javax.swing.JButton Refresh_jP1;
    private javax.swing.JButton Settings_jP4;
    private javax.swing.JLabel Subtitle_jP1;
    private javax.swing.JLabel Subtitle_jP2;
    private javax.swing.JLabel Subtitle_jP3;
    private javax.swing.JLabel Subtitle_jP4;
    private javax.swing.JLabel Subtitle_jP5;
    private javax.swing.JLabel Subtitle_jP6;
    private javax.swing.JLabel Subtitle_jP7;
    private javax.swing.JLabel Subtitle_jP9;
    private javax.swing.JLabel Title_combobox_jP1;
    private javax.swing.JLabel Title_jP1;
    private javax.swing.JLabel Title_jP2;
    private javax.swing.JLabel Title_jP3;
    private javax.swing.JLabel Title_jP4;
    private javax.swing.JLabel Title_jP5;
    private javax.swing.JLabel Title_jP6;
    private javax.swing.JLabel Title_jP7;
    private javax.swing.JLabel Title_jP8;
    private javax.swing.JLabel Title_jP9;
    private javax.swing.JButton add_user_button_jP7;
    private javax.swing.JButton add_user_jP6;
    private javax.swing.JButton auth_button_jP9;
    private javax.swing.JButton create_jP4;
    private javax.swing.JButton create_picture_jP9;
    private javax.swing.JTextField file_path_jP4;
    private javax.swing.JTextField file_path_jP5;
    private javax.swing.JButton gdrive_sync_jP3;
    private javax.swing.JTextField get_auth_code_jP9;
    private javax.swing.JButton google_auth_jP6;
    private javax.swing.JLabel info_text1_jP9;
    private javax.swing.JLabel info_text2_jP10;
    private javax.swing.JLabel info_text2_jP9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jP1;
    private javax.swing.JPanel jP2;
    private javax.swing.JPanel jP3;
    private javax.swing.JPanel jP3_choose;
    private javax.swing.JPanel jP4_create;
    private javax.swing.JPanel jP5_send;
    private javax.swing.JPanel jP6_settings;
    private javax.swing.JPanel jP7_add_user;
    private javax.swing.JPanel jP8_gdrive;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton local_storage_jP3;
    private javax.swing.JButton off_system_jP6;
    private javax.swing.JPasswordField password_jP2;
    private javax.swing.JPasswordField password_jP7;
    private javax.swing.JLabel password_label_jP7;
    private javax.swing.JLabel password_title_jP2;
    private javax.swing.JButton restart_device_jP6;
    private javax.swing.JComboBox<String> rpilist_jP1;
    private javax.swing.JButton select_file_jP4;
    private javax.swing.JButton select_file_jP5;
    private javax.swing.JButton send_button_jP5;
    private javax.swing.JButton send_jP4;
    private javax.swing.JButton start_system_jP6;
    private javax.swing.JTextField user_jP7;
    private javax.swing.JLabel user_label_jP7;
    private javax.swing.JTextField username_jP2;
    private javax.swing.JLabel username_title_jP2;
    private javax.swing.JButton website_button_jP9;
    // End of variables declaration//GEN-END:variables
}
