/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_alfa;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.net.Socket;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author adrix
 */
public class appframe extends javax.swing.JFrame {

    public static String komenda = "";
    public static String USER = "";
    public static String PASS = "";
    public static String host = "";
    public static String ip_route = "";
    public static String full_get_selected = "";
    public static String ip_addr_glob = "";
    public static int port = 0;
    private ArrayList<String> avilible_raspberry = new ArrayList<String>();

    /**
     * Creates new form appframe
     */
    public appframe() {
        setTitle("");
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.JPanel();
        jP1 = new javax.swing.JPanel();
        Title_jP1 = new javax.swing.JLabel();
        Subtitle_jP1 = new javax.swing.JLabel();
        Title_combobox_jP1 = new javax.swing.JLabel();
        rpilist_jP1 = new javax.swing.JComboBox<>();
        Panel_jP1 = new javax.swing.JPanel();
        Refresh_jP1 = new javax.swing.JButton();
        Next_jP1 = new javax.swing.JButton();
        jP2 = new javax.swing.JPanel();
        Title_jP2 = new javax.swing.JLabel();
        Subtitle_jP2 = new javax.swing.JLabel();
        username_title_jP2 = new javax.swing.JLabel();
        username_jP2 = new javax.swing.JTextField();
        password_title_jP2 = new javax.swing.JLabel();
        password_jP2 = new javax.swing.JPasswordField();
        Panel_jP2 = new javax.swing.JPanel();
        Next_jP2 = new javax.swing.JButton();
        Back_jP2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P1.setLayout(new java.awt.CardLayout());

        jP1.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP1.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP1.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP1.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP1.setText("Witaj!");
        Title_jP1.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP1.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP1.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP1.setText("Aby kontynuować wybierz swoje urządzenie z listy poniżej...");
        Subtitle_jP1.setPreferredSize(new java.awt.Dimension(503, 24));

        Title_combobox_jP1.setForeground(new java.awt.Color(149, 152, 154));
        Title_combobox_jP1.setText("Urządzenia podłączone do sieci...");

        rpilist_jP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Przed użyciem odśwież listę urządzeń" }));
        rpilist_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpilist_jP1ActionPerformed(evt);
            }
        });

        Panel_jP1.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP1.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP1.setPreferredSize(new java.awt.Dimension(88, 59));

        Refresh_jP1.setText("Odśwież listę");
        Refresh_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_jP1ActionPerformed(evt);
            }
        });

        Next_jP1.setText("Dalej");
        Next_jP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP1Layout = new javax.swing.GroupLayout(Panel_jP1);
        Panel_jP1.setLayout(Panel_jP1Layout);
        Panel_jP1Layout.setHorizontalGroup(
            Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refresh_jP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP1)
                .addContainerGap())
        );
        Panel_jP1Layout.setVerticalGroup(
            Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP1)
                    .addComponent(Refresh_jP1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP1Layout = new javax.swing.GroupLayout(jP1);
        jP1.setLayout(jP1Layout);
        jP1Layout.setHorizontalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addGroup(jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addComponent(Title_combobox_jP1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rpilist_jP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP1Layout.setVerticalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_combobox_jP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rpilist_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(Panel_jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP1, "panelOne");

        jP2.setBackground(new java.awt.Color(38, 38, 38));

        Title_jP2.setBackground(new java.awt.Color(204, 204, 198));
        Title_jP2.setFont(new java.awt.Font("SF Pro Display", 0, 32)); // NOI18N
        Title_jP2.setForeground(new java.awt.Color(204, 204, 198));
        Title_jP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_jP2.setText("Zaloguj się do urządzenia.");
        Title_jP2.setPreferredSize(new java.awt.Dimension(54, 39));

        Subtitle_jP2.setFont(new java.awt.Font("SF Pro Text", 0, 20)); // NOI18N
        Subtitle_jP2.setForeground(new java.awt.Color(149, 152, 154));
        Subtitle_jP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitle_jP2.setText("Podaj nazwę użytkownika oraz hasło.");
        Subtitle_jP2.setPreferredSize(new java.awt.Dimension(503, 24));

        username_title_jP2.setForeground(new java.awt.Color(149, 152, 154));
        username_title_jP2.setText("Nazwa użytkownika:");

        password_title_jP2.setForeground(new java.awt.Color(149, 152, 154));
        password_title_jP2.setText("Hasło:");

        Panel_jP2.setBackground(new java.awt.Color(28, 28, 28));
        Panel_jP2.setForeground(new java.awt.Color(28, 28, 28));
        Panel_jP2.setPreferredSize(new java.awt.Dimension(88, 59));

        Next_jP2.setText("Dalej");
        Next_jP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jP2ActionPerformed(evt);
            }
        });

        Back_jP2.setText("Wstecz");
        Back_jP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_jP2Layout = new javax.swing.GroupLayout(Panel_jP2);
        Panel_jP2.setLayout(Panel_jP2Layout);
        Panel_jP2Layout.setHorizontalGroup(
            Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next_jP2)
                .addContainerGap())
        );
        Panel_jP2Layout.setVerticalGroup(
            Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jP2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(Panel_jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_jP2)
                    .addComponent(Back_jP2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP2Layout = new javax.swing.GroupLayout(jP2);
        jP2.setLayout(jP2Layout);
        jP2Layout.setHorizontalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_jP2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addGroup(jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title_jP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitle_jP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(username_jP2)
                    .addGroup(jP2Layout.createSequentialGroup()
                        .addGroup(jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_title_jP2)
                            .addComponent(password_title_jP2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(password_jP2))
                .addContainerGap())
        );
        jP2Layout.setVerticalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username_title_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_title_jP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(Panel_jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P1.add(jP2, "panelTwo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rpilist_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpilist_jP1ActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_rpilist_jP1ActionPerformed

    private void Back_jP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jP2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelOne");
    }//GEN-LAST:event_Back_jP2ActionPerformed

    private void Next_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)P1.getLayout();
        card.show(P1,"panelTwo");
        
        full_get_selected = (String)rpilist_jP1.getSelectedItem();
        String[] parts = full_get_selected.split(" ");
        ip_addr_glob = parts[5].substring(0,parts[5].length()-1);
        System.out.println(ip_addr_glob);
        
        
    }//GEN-LAST:event_Next_jP1ActionPerformed

    private void Refresh_jP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_jP1ActionPerformed
        // TODO add your handling code here:
        rpilist_jP1.removeAllItems();

        int timeout=100;
        int port = 1234;
        String ip_addr = "";
        
        Set<String> HostAddresses = new HashSet<>();
            try {
                for (NetworkInterface ni : Collections.list(NetworkInterface.getNetworkInterfaces())) {
                    if (!ni.isLoopback() && ni.isUp() && ni.getHardwareAddress() != null) {
                        for (InterfaceAddress ia : ni.getInterfaceAddresses()) {
                            if (ia.getBroadcast() != null) {  //If limited to IPV4
                                HostAddresses.add(ia.getAddress().getHostAddress());
                                ip_addr = HostAddresses.toString();
                                System.out.println(ip_addr);
                            }
                        }
                    }
                }
            } catch (SocketException e) { }
        
        try {
            int index = ip_addr.indexOf(" ");
            String firststring = ip_addr.substring(0, index);
            System.out.println(firststring);
            
            firststring = firststring.substring(1);
            String subnet = getSubnet(firststring);
            System.out.println("subnet: " + subnet);
            
            for (int i=1;i<254;i++){

                String host = subnet + i;
                System.out.println("Checking :" + host);

                if (InetAddress.getByName(host).isReachable(timeout)){
                    System.out.println(host + " is reachable");
                    try {
                        Socket connected = new Socket(subnet, port);
                    }
                    catch (Exception s) {
                        System.out.println(s);
                    }
                }
            }
        }
        catch(Exception e){
            System.out.println(e);
        }


        Runtime rt_arp = Runtime.getRuntime();
        //System.out.println("Twoje Raspberry PI w sieci: ");
        String[] cmd_arp = { "/bin/bash", "-c", "arp -a | grep 'b8:27:eb'" };

        Process proc_arp = null;
        try {
            proc_arp = rt_arp.exec(cmd_arp);
        } catch (IOException ex) {
            Logger.getLogger(appframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader is_arp = new BufferedReader(new InputStreamReader(proc_arp.getInputStream()));
        String line_arp;
        try {
            while ((line_arp = is_arp.readLine()) != null) {
                String[] parts = line_arp.split(" ");
                System.out.println("Nazwa urządzenia: " + parts[0] + ", adress ip: " + parts[1].substring(1, parts[1].length()-1) + ", adress mac: "+ parts[3]);
                rpilist_jP1.addItem("Nazwa urządzenia: " + parts[0] + ", adress ip: " + parts[1].substring(1, parts[1].length()-1) + ", adress mac: "+ parts[3]);
            }
              } catch (IOException ex) {
            Logger.getLogger(appframe.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Refresh_jP1ActionPerformed

    private void Next_jP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jP2ActionPerformed
        // TODO add your handling code here:
        USER = username_jP2.getText();
        PASS = new String(password_jP2.getPassword());
        
        System.out.println(USER + " " + PASS);
    }//GEN-LAST:event_Next_jP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appframe().setVisible(true);
            }
        });
    }

    public static String getSubnet(String ip_addr) {
        int firstSeparator = ip_addr.lastIndexOf("/");
        int lastSeparator = ip_addr.lastIndexOf(".");
        return ip_addr.substring(firstSeparator+1, lastSeparator+1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_jP2;
    private javax.swing.JButton Next_jP1;
    private javax.swing.JButton Next_jP2;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel Panel_jP1;
    private javax.swing.JPanel Panel_jP2;
    private javax.swing.JButton Refresh_jP1;
    private javax.swing.JLabel Subtitle_jP1;
    private javax.swing.JLabel Subtitle_jP2;
    private javax.swing.JLabel Title_combobox_jP1;
    private javax.swing.JLabel Title_jP1;
    private javax.swing.JLabel Title_jP2;
    private javax.swing.JPanel jP1;
    private javax.swing.JPanel jP2;
    private javax.swing.JPasswordField password_jP2;
    private javax.swing.JLabel password_title_jP2;
    private javax.swing.JComboBox<String> rpilist_jP1;
    private javax.swing.JTextField username_jP2;
    private javax.swing.JLabel username_title_jP2;
    // End of variables declaration//GEN-END:variables
}
